# Generated by Django 3.2.6 on 2021-11-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner Eventos', 'verbose_name_plural': 'Banner Eventos'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Eventos', 'verbose_name_plural': 'Eventos'},
        ),
    ]
