# Generated by Django 3.2.6 on 2022-11-23 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0007_establishment_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
                ('message', models.CharField(max_length=50, verbose_name='Mensagem')),
                ('request_json', models.TextField(blank=True, null=True, verbose_name='JSON da Request')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationcenter_establishment', to='establishment.establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationcenter_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Central de Notificacoes',
                'verbose_name_plural': 'Central de Notificacoes',
            },
        ),
    ]
