# Generated by Django 3.2.6 on 2021-10-01 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comments',
            name='updateAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
