# Generated by Django 3.2.6 on 2021-11-09 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishment', '0005_delete_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereços', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-createAt'], 'verbose_name': 'Comentários', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AlterModelOptions(
            name='schedules',
            options={'verbose_name': 'Horarios', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AddField(
            model_name='establishment',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operators_establishment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='sch_shift',
            field=models.IntegerField(choices=[(0, 'Fechado'), (1, 'Período 1'), (2, '24 horas')]),
        ),
    ]
