# Generated by Django 3.2.6 on 2022-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_auto_20211109_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='logo',
            field=models.URLField(blank=True, max_length=1200, null=True),
        ),
    ]
