# Generated by Django 3.2.6 on 2022-10-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_auto_20211109_0011'),
        ('user', '0003_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='establishments_fav',
            field=models.ManyToManyField(blank=True, help_text='Estabelecimentos Favoritos Favoritos', related_name='gas_favs', to='establishment.Establishment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
