# Generated by Django 3.2.6 on 2022-11-23 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221025_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, verbose_name='Token Push')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='E do App?')),
                ('is_web', models.BooleanField(default=False, verbose_name='E do Admin Web?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
